#!/bin/bash
#
# Run the script 3x in parallel on the Peregrine computer cluster
#
# Usage:
#
# ./run_for_3_rng_seeds
#

cd ..

for i in $(seq 1 3);
do
  sbatch scripts/run_r_script example_9.R $i
done